version: '3'
services:
  service1:
    build: ./service1
    ports:
      - "8000:8000"
    networks:
      - app-network

  service2:
    build: ./service2
    ports:
      - "8001:8001"
    networks:
      - app-network

  service3:
    build: ./service3
    ports:
      - "8002:8002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
